### ISSUE TITLE
Move the project to React

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/TheZalophusBlog#1]
The project uses ejs but we want to replace it React + GraphQL stack which is a new tech and very much in demand.

Create a folder called `New`, cd into it and folllow the tutorial and make sure it works.
Follow the tutorial
https://www.youtube.com/watch?v=7giZGFDGnkc&list=PL55RiY5tL51rG1x02Yyj93iypUuHYXcB_&index=1

PS - No need to add material-ui for the time being. We will be using a different framework called antd. We just need to see it working for now.

Also we just need to see it working, no need to add the events or bookings. Simple user model is okay.

**Comment by InfiniteVerma** [comment]
I'll like to work on this.

**Comment by thebishaldeb** [comment]
Sure. Make sure to do everything in the 'new' folder as we'll do everything from scratch whatever is there in the current folder.

**Comment by thebishaldeb** [comment]
@InfiniteVerma  any progress?

**Comment by InfiniteVerma** [comment]
I've started the tutorials

**Comment by thebishaldeb** [comment]
Cool

**Comment by thebishaldeb** [comment]
@InfiniteVerma Could you understand what needs to be done by now?

**Comment by dev-sankhadip** [comment]
If anyone is not on this, i would like to work on it? Can i go ahead?

**Comment by dev-sankhadip** [comment]
If i am assigned to do it, can you please explain about design. You said no material ui, we will use antd. So should i design components in react?

**Comment by thebishaldeb** [comment]
Sure. Follow the tutorial. Text me on gitter if you got doubts.

**Comment by dev-sankhadip** [comment]
Ok

**Comment by dev-sankhadip** [comment]
I am beginner in graphql, so it might take time to build site. Although i will try to finish it soon.

**Comment by thebishaldeb** [comment]
@dev-sankhadip Update on it?

**Comment by dev-sankhadip** [comment]
I am currently following mentioned tutorials, now i have little bit idea how graphql works. Can you please elaborate what need to be done in react+graphql for this project?

**Comment by thebishaldeb** [comment]
We will build a blogging site using graphql and react similar to the current one in the repo. We will also have login system and other things included.

**Comment by dev-sankhadip** [comment]
Can i use my own design for components?

**Comment by thebishaldeb** [comment]
For this issue, just make sure that graphql  works with react on the `new` folder and user can be created and stored in database.

Designing will be asked later in the other issues.

**Comment by dev-sankhadip** [comment]
And all features currently in node js+ejs, should i add them?

**Comment by thebishaldeb** [comment]
We will do those in the next issues that I will create.

**Comment by dev-sankhadip** [comment]
Ok for now i will kick a fresh start react+graphql with user authentication. Right?

**Comment by dev-sankhadip** [comment]
So fot it i think current both issues will be solved. 1. Move project to react 2. User authentication

**Comment by thebishaldeb** [comment]
User auth would be to create a proper authentication for the user, including register page, login page and home page. If you can do it, well and good. I'll consider both.

**Comment by dev-sankhadip** [comment]
Ok got it, i am on it.

**Comment by thebishaldeb** [comment]
Please do it asap so that we can move to other parts as well.

**Comment by dev-sankhadip** [comment]
I am having semester exams, that's why it's getting late. I will do it soon

**Comment by dev-sankhadip** [comment]
Give time till tomorrow night, i will complete this part.
