### ISSUE TITLE
More fields when signing up.

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/TheZalophusBlog#13]
A user should be able to insert his first name, last name, a unique username, email, password, confirm password (only if password = confirm password, password gets saved, and confirm password doesn't get saved in the database), his profile picture.

Increase the schema accordingly, also also add role which gets saved as 'admin' for now if a new user is created.

The login and sign up should be in different pages.

**Comment by ankushbhardwxj** [comment]
@thebishaldeb I'd like to get this done 👍

**Comment by ankushbhardwxj** [comment]
@thebishaldeb please clarify the password and confirm password thing.

**Comment by thebishaldeb** [comment]
> @thebishaldeb please clarify the password and confirm password thing.

It is basically like it is done in other sites. Two fields, password and confirm password should be there and password should be saved only if the password and confirm password fileds are same.

**Comment by thebishaldeb** [comment]
The confirm password filed need not be saved. It is just needed to verify that user if not typing anything by mistake by asking him to type it again

**Comment by dev-sankhadip** [comment]
Assign me i want this part complete with complete ui

**Comment by thebishaldeb** [comment]
Different issues I will create for the UI. Just  need the functionality now.
