### ISSUE TITLE
Proper error messages while registering or logging in or registering

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/TheZalophusBlog#16]
Proper error meesages should be shown like incorrect password, user doesn't exist, passwords do not match, etc to the users while registering or logging in.

**Comment by dev-sankhadip** [comment]
I will do this. Assign me please

**Comment by thebishaldeb** [comment]
I can assign only after the previous one (blog) is done.

**Comment by dev-sankhadip** [comment]
Ok

**Comment by dev-sankhadip** [comment]
I will like to do this....
