### ISSUE TITLE
Add user authentication

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/TheZalophusBlog#2]
After #1 is done, add user authentication so that each user can log in and see his info inside the `New` folder.

Follow the tutorial - https://www.youtube.com/watch?v=7giZGFDGnkc&list=PL55RiY5tL51rG1x02Yyj93iypUuHYXcB_&index=1

No need to care about designing the page.

**Comment by thebishaldeb** [comment]
A proper login, signup and homepage is needed with login and logout buttons which are present accordingly.

**Comment by ankushbhardwxj** [comment]
@thebishaldeb hey ! I would like to get this done. Please assign me 👍

**Comment by dev-sankhadip** [comment]
Can i go ahead in this part as i was doing it? If yes assign me please.

**Comment by thebishaldeb** [comment]
@dev-sankhadip since @ankingcodes already did most of the part, would be better if you don't do it.
