### ISSUE TITLE
No login page if logged in

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/TheZalophusBlog#23]
User should not see login page if logged in, which is currently possible.

Also update the login page such that it should accept both email or username in a single field and login the person checking the cases in backend accordingly.

**Comment by dev-sankhadip** [comment]
Will fix it

**Comment by dev-sankhadip** [comment]
Can i go ahead?

**Comment by thebishaldeb** [comment]
Sure. Make sure that it is implenented such a way that in future the same thing can be used without redundancy in other pages as well.
