### ISSUE TITLE
Feature to show, edit and delete blogs.

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/TheZalophusBlog#25]
A full page for the blogs, like the old site, when clicked read more, and edit and delete blogs by the user who created it.

Basic functionality, no designing is required as of yet.

The edit and delete buttons should be visible only if the userid matches the user id of the blog.

**Comment by devyaniChoubey** [comment]
@thebishaldeb  can I work on this issue?

**Comment by thebishaldeb** [comment]
Sure. We are working on the `new` folder using Graphql React. Make sure to work on that and not the one using ejs. That is only for reference.

Do not use bootstrap or semantic UI here. Try using antd components.

**Comment by devyaniChoubey** [comment]
okkk

**Comment by devyaniChoubey** [comment]
I am not able to signup please help

**Comment by devyaniChoubey** [comment]
![Screenshot (31)](https://user-images.githubusercontent.com/52153085/70694242-21e58580-1ce5-11ea-93a6-f2d86948b5e1.png)

**Comment by thebishaldeb** [comment]
Check in the terminal if mongodb is connected. 
Check if it is already saved in the database and try logging in with that.

**Comment by thebishaldeb** [comment]
Update?

**Comment by devyaniChoubey** [comment]
I am working on it.
I will complete it by today evening

**Comment by AmanR28** [comment]
I want to work on it.

**Comment by thebishaldeb** [comment]
@AmanR28 sure!

**Comment by thebishaldeb** [comment]
@AmanR28 just to make things clear, you are supposed to work on the `new` folder, not the `old` one.

**Comment by ankushbhardwxj** [comment]
@thebishaldeb I would like to get this done , if there's no update from @AmanR28

**Comment by thebishaldeb** [comment]
@AmanR28 update?

**Comment by AmanR28** [comment]
My area internet got blocked by the government, so this delay.
So update and delete blog resolvers are left.

**Comment by AmanR28** [comment]
Done

**Comment by thebishaldeb** [comment]
@ankingcodes still interested?
