### ISSUE TITLE
The home page shhould be visible to all.

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/TheZalophusBlog#26]
The home page where blogs is shown should be visible to all.
And depending on if an user is logged in or out, buttons should be should at the top, i.e., if logged in, log out button, and  if logged out, sign in button.

**Comment by dev-sankhadip** [comment]
All the current blogs will be visible to all users who visits site's homepage?

**Comment by dev-sankhadip** [comment]
Can you please elaborate how it should be?

**Comment by thebishaldeb** [comment]
Currently the home page is only show to the person logged in. But it should be present for everyone. 
In the nabar, there should be login and logout buttons accordingly. If he clicks logged out, he is redirect to the home page but with signin button in navbar.
In case of sign in button, it should redirect to login page.

Also the hompage should be in `"/"` and login/signup page in `"signin"` / `"signup"` respectively. Change the routes accordingly

**Comment by dev-sankhadip** [comment]
So all blog posted by all users will be visible to viewers?
