### ISSUE TITLE
Design the login and registration page.

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/TheZalophusBlog#31]
THe login and registration page needs designing. Use antd components for the same.

https://ant.design/docs/react/customize-theme - reference. Check out the components section.

**Comment by sk044** [comment]
I can work on this issue..

**Comment by thebishaldeb** [comment]
Assigned

**Comment by sk044** [comment]
okay i am working on it

**Comment by thebishaldeb** [comment]
Update?

**Comment by sk044** [comment]
working .. i'll complete it within 2 days ... as currently i am having some medical issues...
