### ISSUE TITLE
Design the home page.

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/TheZalophusBlog#32]
https://ant.design/docs/react/customize-theme - antd cards and other components should be used for the same.

**Comment by abhisheknaiidu** [comment]
@thebishaldeb  want to work on this!

**Comment by thebishaldeb** [comment]
Assigned to you @abhisheknaiidu Make sure to use only antd components and and remove other components and classes of bootstrap, semantic-UI or any other.
