### ISSUE TITLE
Profile page for the user and edit profile form.

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/TheZalophusBlog#33]
It should be using /:username.

User antd Components for the same.  There should be another page to edit his profile linked to that profile by a button where he can add his description and other things.

Take reference from https://ant.design/docs/react/customize-theme to design.

Note that password cannot be changed from that edit profile page.

**Comment by dev-sankhadip** [comment]
i want to do it, please assign me

**Comment by thebishaldeb** [comment]
One issue at a time. Please finish the other one first.

**Comment by dev-sankhadip** [comment]
Assign me please

**Comment by thebishaldeb** [comment]
Issue not solved yet and can be taken up.
