### ISSUE TITLE
Move to `Old` Folder

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/TheZalophusBlog#4]
Create a new folder called `Old` in the repo and move everything except README and LICENSE in that folder.

Update the README after that to `cd TheZalophusBlog/Old` to see the old site. Make sure the site works even after that.

**Comment by dev-sankhadip** [comment]
I have created pull request of this. Can you please check it?

**Comment by dev-sankhadip** [comment]
Sorry, by mistake i have closed that PR, Was gonna click comment, close and comment has been clicked.

**Comment by thebishaldeb** [comment]
I have opened it again. Read the issue carefully, what is asked to be updated in README.
