### ISSUE TITLE
on clicking Refresh the entire form which is entered is loosing its state

### ISSUE THREAD

**Issue by pratik0316** [NJACKWinterOfCode/TheZalophusBlog#45]
![Screenshot from 2019-12-28 15-45-10](https://user-images.githubusercontent.com/44219625/71542243-fbcd1000-2989-11ea-910b-ec52121f7648.png)

 upon refreshing it again changes to
![Screenshot from 2019-12-28 15-48-42](https://user-images.githubusercontent.com/44219625/71542234-c45e6380-2989-11ea-885b-8116e8abcefc.png)

**Comment by thebishaldeb** [comment]
We are using posst method and not saving the state either. No need of raising such issues currently when it is not even completed being worked on yet.
